import Navigation from "@/components/navigation";
import "./globals.css";
import { Container } from "@mui/material";

export const metadata = {
  title: {
    template: "%s / Next Blog App",
    default: "Welcome / Next Blog App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navigation />
        </header>
        <main>
          <Container sx={{ my: 3 }}>{children}</Container>
        </main>
      </body>
    </html>
  );
}